version: "3.9"

networks:
  ephemery_net:
    driver: bridge

volumes:
  geth_data:
  nimbus_data:

services:
  execution:
    image: ethereum/client-go:stable
    container_name: ephemery-geth-snap
    command:
      - --datadir=/data
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/jwt/jwt.hex
      - --syncmode=snap
      - --cache=1024
    ports:
      - "8545:8545"   # JSON-RPC
      - "8551:8551"   # Engine API
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - geth_data:/data
      - ./config/ephemery:/config:ro
      - ./jwt:/jwt:ro
    restart: unless-stopped
    networks:
      - ephemery_net

  consensus:
    image: statusim/nimbus-eth2:multiarch-latest
    container_name: ephemery-nimbus
    user: "0:0"
    depends_on:
      - execution
    command:
      - --data-dir=/data
      - --web3-url=http://execution:8551
      - --jwt-secret=/jwt/jwt.hex
      - --rest
      - --rest-address=0.0.0.0
      - --rest-port=5052
      - --network=/config/ephemery
      - --insecure-netkey-password
    ports:
      - "5052:5052"   # Beacon API
      - "9001:9000/tcp"
      - "9001:9000/udp"
    volumes:
      - nimbus_data:/data:Z
      - ./config/ephemery:/config/ephemery:ro
      - ./jwt:/jwt:ro
    restart: unless-stopped
    networks:
      - ephemery_net